repos:
  - repo: local
    hooks:
      - id: tox
        name: tox
        entry: poetry run tox
        language: system
        pass_filenames: false
        stages: [commit]
      - files: ^git_plan/
        id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        stages: [commit]
        types: [file, python]
      - files: ^git_plan/
        id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        stages: [commit]
        types: [file, python]
