repos:
  - repo: local
    hooks:
      - id: tox
        name: tox
        entry: uv run tox
        language: system
        pass_filenames: false
        stages: [commit]
      - files: ^git_plan/
        id: ruff
        name: ruff
        entry: uv run ruff format
        language: system
        stages: [commit]
        types: [file, python]
      - files: ^git_plan/
        id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        stages: [commit]
        types: [file, python]
