[project]
name = "git-plan"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.8"
dependencies = [
    "cachetools>=5.5.0",
    "dependency-injector>=4.44.0",
    "humanize>=4.10.0",
    "inquirer>=3.1.4",
    "rich>=13.9.4",
]

[tool.uv]
dev-dependencies = [
    "coverage>=7.6.1",
    "pre-commit>=3.5.0",
    "pyright>=1.1.390",
    "pytest>=8.3.4",
    "ruff>=0.8.2",
    "tox>=4.23.2",
]
package = true

[project.scripts]
git-plan = 'git_plan.__cli__:main'
gp = 'git_plan.__cli__:main'

[tool.pylint.MASTER]
extension-pkg-whitelist = "dependency_injector"
generated-members = "dependency_inector.*, subcommand, wire"
good-names = "id, fp, e"
max-line-length = 120

[tool.isort]
known_first_party = ['git_plan']

[tool.ruff]
line-length = 120
