[project]
name = "git-plan"
version = "0.2.3"
description = "A better personal workflow for git."
license = "MIT"
authors = [
    { name = "Rory Byrne", email = "rory@rory.bio" }
]
repository = "https://github.com/synek/git-plan"
readme = "README.md"

### DEPENDENCIES

requires-python = ">= 3.8"
dependencies = [
    "dependency-injector>=4.41.0",
    "rich>=13.7.1",
    "inquirer>=3.3.0",
    "humanize>=4.10.0",
    "dataclasses>=0.6",
    "cachetools>=5.4.0",
]

### ENTRYPOINTS

[project.scripts]
git-plan = "git_plan.__cli__:main"
gp = "git_plan.__cli__:main"

[tool.rye]
managed = true
dev-dependencies = [
    "pylint>=3.2.6",
    "coverage>=7.6.0",
    "pre-commit>=3.7.1",
    "tox>=4.16.0",
    "pyright>=1.1.372",
    "black>=24.4.2",
    "isort>=5.13.2",
    "flake8>=7.1.0",
    "flake8-pyproject>=1.2.3",
    "pytest>=8.3.1",
]

### TOOLS

[tool.black]
line-length = 100

[tool.isort]
known_first_party = ['git_plan']
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.pylint]
max-line-length = 100
disable = ["logging-fstring-interpolation"]
extension-pkg-whitelist = "dependency_injector"
generated-members = "dependency_inector.*, subcommand, wire"
good-names = "id, fp, e"

[tool.flake8]
max-line-length = 100
extend-ignore = "E266"
disable = ["logging-fstring-interpolation"]

[tool.pyright]
include = ["git_plan", "tests" ]

[tool.pytest]
asyncio_mode = "auto"

[tool.pytest.ini_options]
log_format = "%(asctime)s %(levelname)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"

### BUILD

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["git_plan"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
