[tox]
envlist = py38, py39, py310, py311
isolated_build = True

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311

[testenv]
setenv =
    SETUPTOOLS_USE_DISTUTILS=stdlib
deps =
    setuptools
    pytest
    coverage
commands =
    coverage run -m pytest -s
    coverage report
